### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by nlvivar** [teneighty/moss#6]
Where is the config file located? I so happy that I found this. Thanks for developing it.

**Comment by teneighty** [comment]
Sorry for the delay with this. Config files is kind of hard coded in the application. See the [assets folder](https://github.com/teneighty/moss/tree/master/moss/src/main/assets) for the configs that are shipped with moss.

You can override it by placing your own config on your sdcard and changing your settings to point to that config file.

**Comment by nlvivar** [comment]
Thanks for the reply. I'll start experimenting with it. No problem with the delay. I only poked around for a .config file just like Conky. When I couldn't figure it out, I just gave up. ;-)
